#!/bin/bash

BATTINFO=`acpi -b`
if [[ `echo "$BATTINFO" | grep Discharging | cut -f 4 -d " " | cut -f 1 -d "%"` -lt 15 ]];
then
    eval "notify-send 'Low battery' '$BATTINFO'"
    eval "zenity --warning --text='$BATTINFO' --ellipsize"
fi
