#!/bin/bash

export DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/1001/bus"

BATTINFO=`acpi -b`
CONDITION=`acpi -b | grep "Battery 0"|grep Discharging | cut -f 4 -d " " | cut -f 1 -d "%"`

echo "$CONDITION"

if [ ! -z "$CONDITION" ] && [ $CONDITION -lt 15 ];
then
    eval "/usr/bin/notify-send 'Low battery' '$BATTINFO'"
    eval "/usr/bin/zenity --warning --text='$BATTINFO' --ellipsize"
fi
